### ISSUE TITLE
Compressed resources file

### ISSUE THREAD

**Issue by laraolmos** [fra82/textdigester#1]
The compressed .tar.gz file downloaded from your "How to import TextDigester in your Java project" readme section is corrupted and it isn't possible to get the TextDigester properties file. Could you fix it, please? Thanks!

**Comment by fra82** [comment]
Thanks for pointing this out! It should be fixed.

You can download the property file of TextDigester from: http://www.backingdata.org/textdigester/TextDigesterConfig.properties

The resource folder can be downloaded from: 
* http://www.backingdata.org/textdigester/TEXTDIGESTER_RESOURCES_v_0_1.tar.gz (TAR.GZ)
* http://www.backingdata.org/textdigester/TEXTDIGESTER_RESOURCES_v_0_1.zip (ZIP)

**Comment by laraolmos** [comment]
All fixed, thank you!

**Comment by laraolmos** [comment]
During the execution of the **centroid embedding summarize model** for an **english text** I have found that the _**enwiki_parw2vec.zip**_ is missing in the resources compressed file, because of the error: 

edu.upf.taln.textdigester.setting.exception.TextDigesterException: Impossible to read embedding model for English from file: '(...)/resources/embeddingmodels/enwiki_parw2vec.zip'
        at edu.upf.taln.textdigester.resource.lex.WikipediaSentenceEmbeddingModel.loadEmbeddingModel(WikipediaSentenceEmbeddingModel.java:98)
        at (...)

Could you add it, please? Thank you!

**Comment by nishresthani** [comment]
Hi
Still missing enwiki_parw2vec.zip in resource folder. 
Hope to solve soon

Thanks
Shrestha
